# Generated by Django 3.0.6 on 2020-07-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='photo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
